---
apiVersion: v1
kind: Template
labels:
  app: gaia-alerter
  template: gaia-alerter
metadata:
  name: phabricator
  template.openshift.io/bindable: "false"
parameters:
- displayName: Name
  name: NAME
  required: true
  value: gaia-alerter
- displayName: Git Repository
  name: GIT_REPO
  required: true
  value: https://github.com/certusone/chain_exporter

objects:

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      template.alpha.openshift.io/wait-for-ready: "true"
    name: ${NAME}
  spec:
    replicas: 1
    selector:
      name: ${NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: ${NAME}
      spec:
        containers:
          - name: gaia-alerter
            image: gaia-exporter:latest
            command:
              - /opt/app-root/go/bin/alerter
            env:
              - name: "DB_HOST"
                value: "postgres-chain:5432"
              - name: "DB_USER"
                value: "postgres"
              - name: "DB_PW"
                value: "mypwd"
              - name: "RAVEN_DSN"
                value: "<INSERT_RAVEN_DSN>"
              - name: "ADDRESS"
                value: "<INSERT_VAL_ADDRESS>"
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${NAME}
        from:
          kind: ImageStreamTag
          name: gaia-exporter:latest
      type: ImageChange
    - type: ConfigChange