---
apiVersion: v1
kind: Template
labels:
  app: gaia-exporter
  template: gaia-exporter
metadata:
  name: phabricator
  template.openshift.io/bindable: "false"
parameters:
- displayName: Name
  name: NAME
  required: true
  value: gaia-exporter
- displayName: Git Repository
  name: GIT_REPO
  required: true
  value: https://github.com/certusone/chain_exporter

objects:

- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ${NAME}
  spec:
    # this allows k8s objects to directly reference this image stream
    lookupPolicy:
      local: true

- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}:latest
    postCommit: {}
    runPolicy: Serial
    source:
      git:
        uri: ${GIT_REPO}
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: golang-s2i:1.10
        env:
          - name: S2I_GOPKG
            value: github.com/certusone/chain_exporter
      type: Source
    triggers:
    - imageChange: {}
      type: ImageChange
    - type: ConfigChange

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      template.alpha.openshift.io/wait-for-ready: "true"
    name: ${NAME}
  spec:
    replicas: 1
    selector:
      name: ${NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: ${NAME}
      spec:
        containers:
          - name: gaia-exporter
            image: gaia-exporter:latest
            command:
              - /opt/app-root/go/bin/chain_exporter
            env:
              - name: "GAIA_URL"
                value: "http://gaia-node1:26657"
              - name: "DB_HOST"
                value: "postgres-chain:5432"
              - name: "DB_USER"
                value: "postgres"
              - name: "DB_PW"
                value: "mypwd"
              - name: "LCD_URL"
                value: "https://gaia-lcd:1317"
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${NAME}
        from:
          kind: ImageStreamTag
          name: gaia-exporter:latest
      type: ImageChange
    - type: ConfigChange