---
apiVersion: v1
kind: Template
labels:
  app: gaia-lcd
  template: gaia-lcd
metadata:
  name: gaia-lcd
  template.openshift.io/bindable: "false"
parameters:
- displayName: Name
  name: NAME
  required: true
  value: gaia-lcd

objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      template.alpha.openshift.io/wait-for-ready: "true"
    name: ${NAME}
  spec:
    replicas: 1
    selector:
      name: ${NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: ${NAME}
      spec:
        containers:
          - name: gaia-lcd
            image: gaiad:latest
            command:
              - /opt/app-root/go/bin/gaiacli
              - rest-server 
              - "--node=tcp://gaia-node1:26657"
              - "--trust-node"
              - "--laddr=tcp://:1317"
            ports:
            - containerPort: 1317
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${NAME}
        from:
          kind: ImageStreamTag
          name: gaiad:latest
      type: ImageChange
    - type: ConfigChange

- apiVersion: v1
  kind: Service
  metadata:
    name: ${NAME}
  spec:
    ports:
    - name: lcd
      port: 1317
    selector:
      name: ${NAME}
- apiVersion: v1
  kind: Route
  metadata:
    name: gaia-lcd
  spec:
    port:
      targetPort: lcd
    tls:
      termination: edge
    to:
      kind: Service
      name: gaia-lcd
      weight: 100
    wildcardPolicy: None
