---
apiVersion: v1
kind: Template
labels:
  app: postgres-chain
  template: postgres-chain
parameters:
- displayName: Name
  name: NAME
  required: true
  value: postgres-chain

objects:

- apiVersion: v1
  kind: ImageStream
  metadata:
    name: postgres
  spec:
    lookupPolicy:
      local: true
    tags:
    - from:
        kind: DockerImage
        name: centos/postgresql-96-centos7:latest
      name: latest
      referencePolicy:
        type: Source

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      template.alpha.openshift.io/wait-for-ready: "true"
    name: ${NAME}
  spec:
    replicas: 1
    selector:
      name: ${NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: ${NAME}
      spec:
        containers:
        - image: ' '
          imagePullPolicy: IfNotPresent
          name: ${NAME}
          ports:
          - containerPort: 5432
          volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: ${NAME}-data
          env:
          - name: POSTGRESQL_ADMIN_PASSWORD
            value: "mypwd"
        volumes:
        - name: ${NAME}-data
          emptyDir: {}
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${NAME}
        from:
          kind: ImageStreamTag
          name: postgres:latest
      type: ImageChange
    - type: ConfigChange

- apiVersion: v1
  kind: Service
  metadata:
    name: ${NAME}
  spec:
    ports:
    - name: postgres
      port: 5432
    selector:
      name: ${NAME}
