# node-exporter is an optional component that collects host level metrics from the nodes
# in the cluster. This group of resources will require the 'hostaccess' level of privilege, which
# should only be granted to namespaces that administrators can access.
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: prometheus-blackbox-exporter
  # You must grant hostaccess via: oadm policy add-scc-to-user -z prometheus-blackbox-exporter hostaccess
  # in order for the node-exporter to access the host network and mount /proc and /sys from the host
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      prometheus.io/scrape: "true"
    labels:
      app: prometheus-blackbox-exporter
    name: prometheus-blackbox-exporter
  spec:
    clusterIP: None
    ports:
    - name: scrape
      port: 9115
      protocol: TCP
      targetPort: 9115
    selector:
      app: prometheus-blackbox-exporter
- apiVersion: extensions/v1beta1
  kind: DaemonSet
  metadata:
    name: prometheus-blackbox-exporter
    labels:
      app: prometheus-blackbox-exporter
      role: monitoring
  spec:
    updateStrategy:
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: prometheus-blackbox-exporter
          role: monitoring
        name: prometheus-exporter
      spec:
        hostNetwork: true
        serviceAccountName: prometheus-blackbox-exporter
        containers:
        - image: prom/blackbox-exporter:v0.12.0
          name: blackbox-exporter
          securityContext:
            capabilities:
              add:
                - NET_RAW
          ports:
          - containerPort: 9115
            name: scrape
          resources:
            requests:
              memory: 30Mi
              cpu: 100m
            limits:
              memory: 50Mi
              cpu: 200m