---
apiVersion: v1
kind: Template
labels:
  app: kafka
  template: kafka
parameters:
- displayName: Name
  name: NAME
  required: true
  value: kafka

objects:

- apiVersion: v1
  kind: ImageStream
  metadata:
    name: kafka
  spec:
    lookupPolicy:
      local: true
    tags:
    - from:
        kind: DockerImage
        name: wurstmeister/kafka:latest
      name: latest
      referencePolicy:
        type: Source

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      template.alpha.openshift.io/wait-for-ready: "true"
    name: ${NAME}
  spec:
    replicas: 1
    selector:
      name: ${NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: ${NAME}
      spec:
        containers:
        - image: ' '
          imagePullPolicy: IfNotPresent
          name: ${NAME}
          ports:
          - containerPort: 9092
          env:
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: "kafka"
            - name: KAFKA_CREATE_TOPICS
              value: "topic:1:1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "${NAME}-zk:2181"
            - name: KAFKA_PORT
              value: "9092"
            
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${NAME}
        from:
          kind: ImageStreamTag
          name: kafka:latest
      type: ImageChange
    - type: ConfigChange

- apiVersion: v1
  kind: Service
  metadata:
    name: ${NAME}
  spec:
    ports:
    - name: kafka
      port: 9092
    selector:
      name: ${NAME}

- apiVersion: v1
  kind: ImageStream
  metadata:
    name: zookeeper
  spec:
    lookupPolicy:
      local: true
    tags:
    - from:
        kind: DockerImage
        name: wurstmeister/zookeeper:latest
      name: latest
      referencePolicy:
        type: Source

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      template.alpha.openshift.io/wait-for-ready: "true"
    name: ${NAME}-zk
  spec:
    replicas: 1
    selector:
      name: ${NAME}-zk
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: ${NAME}-zk
      spec:
        containers:
        - image: ' '
          imagePullPolicy: IfNotPresent
          name: ${NAME}-zk
          ports:
          - containerPort: 2181
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${NAME}-zk
        from:
          kind: ImageStreamTag
          name: zookeeper:latest
      type: ImageChange
    - type: ConfigChange

- apiVersion: v1
  kind: Service
  metadata:
    name: ${NAME}-zk
  spec:
    ports:
    - name: zookeeper
      port: 2181
    selector:
      name: ${NAME}-zk